import { registerCoreTools } from './core';
import { registerWebSearchTools } from './webSearch';
import { registerFilesystemTools } from './filesystem';
import { registerControlTools } from './controls';
import { registerCodeTools } from './code';
import { registerMemoryTools } from './memory';
import { registerLocationTools } from './location';
import { registerTaskTools } from './tasks';
import { registerNoteTools } from './notes';
import { registerAutonomyTools } from './autonomy';
import { registerPowerTools } from './powerTools';
import { registerDeviceIntegrationTools } from './deviceIntegration';
import { registerSocialMediaTools } from './socialMedia';
import { registerConnectorTools } from './connectors';
import { registerGatewayTools } from './gateway';
import { registerTelegramTools } from './telegram';
import { registerTerminalTools } from './terminal';
import { registerGatewayDaemonTools } from './gatewayDaemon';
import { registerClipboardTools } from './clipboard';
import { registerHapticsTools } from './haptics';
import { registerShareTools } from './share';
import { registerGeolocationTools } from './geolocation';
import { registerNotificationTools } from './notifications';
import { registerDeviceTools } from './device';
import { registerBuildTools } from './build';
import { registerSandboxTools } from './sandbox';
import { registerCameraTools } from './camera';
import { registerFilegenTools } from './filegen';
import { registerDocumentTools } from './documents';
import { registerRagTools } from './rag';
import { registerEmailTools } from './email';
import { registerCalendarTools } from './calendar';
import { registerMessagingTools } from './messaging';
import { registerPersonalTools } from './personal';
import { registerSshTools } from './ssh';
import { registerDatabaseTools } from './database';
import { registerWebsocketTools } from './websocket';
import { registerFileTools } from './filetool';
import { registerNetworkTools } from './network';
import { registerSecurityTools } from './security';
import { registerCreatePdfTool } from './createPdf';
import { registerMediaAccessTools } from './mediaAccess';
import { registerSmartHomeTools } from './smartHome';
import { registerNeuraTools } from './neura';
import { registerBrowserAutomationTools } from './browserAutomation';
import { registerPdfTools } from './readPdf';
import { registerAdvancedTools } from './advanced';
import { registerCustomInstructionTools } from './customInstructions';
import { registerIdentityTools } from './identity';
import { registerProviderHealthTools } from './providerHealth';
import { registerResponseCacheTools } from './responseCache';
import { registerLongRunningTools } from './longRunning';
import { registerBrainCloudTools } from './brainCloud';
import { registerMCPTools } from './mcp';
import { registerPluginTools } from './plugin';
import { registerSearchConfigTools } from './searchConfig';
import { registerCodeExecTools } from './codeExec';
import { registerCodeHistoryTools } from './codeHistory';
import { registerSessionTools } from './session';
import { registerPersonalEnhancedTools } from './personalEnhanced';
import { registerScheduledTaskTools } from './scheduledTasks';

export function registerAllTools() {
  registerCoreTools();
  registerWebSearchTools();
  registerFilesystemTools();
  registerControlTools();
  registerCodeTools();
  registerMemoryTools();
  registerLocationTools();
  registerTaskTools();
  registerNoteTools();
  registerAutonomyTools();
  registerPowerTools();
  registerDeviceIntegrationTools();
  registerSocialMediaTools();
  registerConnectorTools();
  registerGatewayTools();
  registerTelegramTools();
  registerTerminalTools();
  registerGatewayDaemonTools();
  registerClipboardTools();
  registerHapticsTools();
  registerShareTools();
  registerGeolocationTools();
  registerNotificationTools();
  registerDeviceTools();
  registerBuildTools();
  registerSandboxTools();
  registerCameraTools();
  registerFilegenTools();
  registerDocumentTools();
  registerRagTools();
  registerEmailTools();
  registerCalendarTools();
  registerMessagingTools();
  registerPersonalTools();
  registerSshTools();
  registerDatabaseTools();
  registerWebsocketTools();
  registerFileTools();
  registerNetworkTools();
  registerSecurityTools();
  registerCreatePdfTool();
  registerMediaAccessTools();
  registerSmartHomeTools();
  registerNeuraTools();
  registerBrowserAutomationTools();
  registerPdfTools();
  registerAdvancedTools();
  registerCustomInstructionTools();
  registerIdentityTools();
  registerProviderHealthTools();
  registerResponseCacheTools();
  registerLongRunningTools();
  registerBrainCloudTools();
  registerMCPTools();
  registerPluginTools();
  registerSearchConfigTools();
  registerCodeExecTools();
  registerCodeHistoryTools();
  registerSessionTools();
  registerPersonalEnhancedTools();
  registerScheduledTaskTools();
}
