import React, { useState, useEffect } from 'react';
import { useGiaStore } from '../store/useGiaStore';
import { templateLearning } from '../services/TemplateLearning';
import { Zap, Clock, Target, RotateCw, GraduationCap, BookOpen, Code, Calendar, Bug, GitBranch, FileCode, Zap as ZapIcon } from 'lucide-react';

interface RecommendedTemplate {
  id: string;
  label: string;
  prompt: string;
  color: string;
  icon: string;
  tags: string[];
  relevanceScore: number;
  adaptation?: string;
  difficulty?: string;
  isAutoGenerated?: boolean;
  usageCount?: number;
}

interface TemplateSelectorProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TemplateSelector: React.FC<TemplateSelectorProps> = ({ isOpen, onClose }) => {
  const [templates, setTemplates] = useState<RecommendedTemplate[]>([]);
  const [selectedTemplate, setSelectedTemplate] = useState<RecommendedTemplate | null>(null);
  const [particles, setParticles] = useState<Array<{id: number, x: number, y: number, color: string}>>([]);
  const [userContext, setUserContext] = useState<Record<string, unknown> | null>(null);

  useEffect(() => {
    if (isOpen) {
      initializeTemplates();
    }
  }, [isOpen]);

  const initializeTemplates = () => {
    const currentModule = useGiaStore.getState().currentModule;
    const recentTopics: string[] = [];
    const activeTools: string[] = [];
    const hours = new Date().getHours();
    const timeOfDay = hours < 12 ? 'morning' : hours < 18 ? 'afternoon' : 'evening';
    const device = window.innerWidth < 768 ? 'mobile' : 'desktop';
    const sessionId = 'session-' + Date.now();

    const userContext: Record<string, unknown> = {
      currentModule,
      recentTopics,
      activeTools,
      timeOfDay,
      device,
      sessionId
    };
    setUserContext(userContext);

    const allTemplates = templateLearning.getAllTemplates();
    const personalized = allTemplates
      .map(template => ({
        ...template,
        // Real relevanceScore comes from actual usage tracking (TemplateLearning).
        // Templates without a tracked score get a flat neutral default — never
        // a random number dressed up as a personalization signal.
        relevanceScore: template.relevanceScore ?? 0.5,
        adaptation: template.isAutoGenerated ? 'Generated based on your usage patterns' : undefined
      }))
      .filter(template => template.relevanceScore > 0.2)
      .sort((a, b) => b.relevanceScore - a.relevanceScore)
      .slice(0, 12);

    setTemplates(personalized);

    if (personalized.length > 0) {
      setSelectedTemplate(personalized[0]);
    }
  };

  const handleTemplateSelect = (template: RecommendedTemplate, index: number) => {
    setSelectedTemplate(template);
    createParticleEffect(index);

    templateLearning.recordTemplateUse(template.id, userContext || {});

    useGiaStore.getState().setPendingInput(template.prompt);
    onClose();
  };

  const createParticleEffect = (index: number) => {
    const newParticles = Array.from({ length: 20 }, (_, i) => ({
      id: Date.now() + i,
      x: 50 + Math.cos((index * 72 + i * 50) * Math.PI / 180) * 100,
      y: 50 + Math.sin((index * 72 + i * 50) * Math.PI / 180) * 100,
      color: templates[index]?.color || '#a855f7'
    }));

    setParticles(newParticles);
    setTimeout(() => setParticles([]), 1000);
  };

  const handleKeyDown = (e: React.KeyboardEvent, template: RecommendedTemplate, index: number) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handleTemplateSelect(template, index);
    } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
      e.preventDefault();
      const prevIndex = templates.length > 0 ? (index - 1 + templates.length) % templates.length : 0;
      handleTemplateSelect(templates[prevIndex], prevIndex);
    } else if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
      e.preventDefault();
      const nextIndex = templates.length > 0 ? (index + 1) % templates.length : 0;
      handleTemplateSelect(templates[nextIndex], nextIndex);
    }
  };

  const getIconComponent = (iconName: string) => {
    const iconMap: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
      'zap': ZapIcon,
      'clock': Clock,
      'target': Target,
      'rotate-cw': RotateCw,
      'graduation-cap': GraduationCap,
      'book-open': BookOpen,
      'code': Code,
      'link': Code,
      'calendar': Calendar,
      'bug': Bug,
      'git-branch': GitBranch,
      'file-code': FileCode,
      'sparkles': ZapIcon,
    };
    return iconMap[iconName] || ZapIcon;
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm">
      <div className="flex items-center justify-center min-h-screen p-4">
        <div className="bg-gray-900 border border-gray-700 rounded-2xl shadow-2xl w-full max-w-5xl max-h-[90vh] overflow-hidden">
          <div className="p-6 border-b border-gray-800 bg-gray-950/50">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 flex items-center justify-center">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <h2 className="text-2xl font-bold text-white">Smart Template Selector</h2>
              </div>
              <button
                onClick={onClose}
                className="p-2 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-400 hover:text-white transition-colors"
              >
                ×
              </button>
            </div>
            <div className="flex items-center gap-4 text-sm text-gray-400">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4" />
                <span>Auto-rotate enabled</span>
              </div>
              <div className="flex items-center gap-2">
                <Target className="w-4 h-4" />
                <span>{templates.length} adaptive templates</span>
              </div>
              {selectedTemplate?.isAutoGenerated && (
                <div className="flex items-center gap-2">
                  <RotateCw className="w-4 h-4" />
                  <span>AI-generated</span>
                </div>
              )}
            </div>
          </div>

          <div className="relative p-8 overflow-hidden">
            <div className="relative aspect-square max-w-2xl mx-auto">
              <div
                className="absolute inset-0 rounded-full border-2 border-purple-500/20 animate-[spin_20s_linear_infinite] opacity-30"
                style={{
                  background: 'conic-gradient(from 0deg at 50% 50%, transparent 0deg, rgba(168, 85, 247, 0.1) 90deg, transparent 180deg)'
                }}
              />

                {templates.map((template, index) => {
                  const angle = index * 72;
                  const radius = 120;
                  const x = 50 + Math.cos(angle * Math.PI / 180) * radius;
                  const y = 50 + Math.sin(angle * Math.PI / 180) * radius;

                  return (
                    <button
                      key={template.id}
                      className="absolute transform -translate-x-1/2 -translate-y-1/2 transition-all duration-300 ease-out"
                      style={{
                        left: `${x}%`,
                        top: `${y}%`,
                        '--angle': angle,
                      } as React.CSSProperties}
                      onClick={() => handleTemplateSelect(template, index)}
                      onKeyDown={(e) => handleKeyDown(e, template, index)}
                      tabIndex={0}
                      aria-label={`${template.label}, selected: ${selectedTemplate?.id === template.id ? 'yes' : 'no'}, ${template.relevanceScore > 0.8 ? 'high relevance' : 'normal'} ${template.isAutoGenerated ? ', AI-generated' : ''}`}
                    >
                    <div
                      className={`w-20 h-20 rounded-full border-2 border-current backdrop-blur-md bg-opacity-80 flex items-center justify-center transition-all duration-300 hover:scale-110 hover:z-10 ${selectedTemplate?.id === template.id ? 'scale-125 z-10' : 'scale-100'}`}
                      style={{
                        borderColor: template.color,
                        backgroundColor: `${template.color}20`,
                        boxShadow: selectedTemplate?.id === template.id
                          ? `0 0 30px ${template.color}80`
                          : 'none'
                      }}
                    >
                      <div className="text-center">
                        {(() => {
                          const IconComponent = getIconComponent(template.icon);
                          return <IconComponent className="w-6 h-6 mx-auto mb-1" style={{ color: template.color }} />;
                        })()}
                        <span
                          className="text-xs font-medium"
                          style={{ color: template.color }}
                        >
                          {template.label}
                        </span>
                      </div>
                    </div>

                    {template.relevanceScore > 0.8 && (
                      <div
                        className="absolute -top-1 -right-1 w-4 h-4 rounded-full bg-gradient-to-r from-yellow-400 to-orange-500 animate-pulse"
                      />
                    )}

                    {template.isAutoGenerated && (
                      <div className="absolute -bottom-1 -left-1 w-4 h-4 rounded-full bg-gradient-to-r from-blue-400 to-purple-500 animate-bounce">
                        <div className="w-full h-full rounded-full bg-blue-400/30 animate-ping" />
                      </div>
                    )}
                  </button>
                );
              })}

              {particles.map(particle => (
                <div
                  key={particle.id}
                  className="absolute w-2 h-2 rounded-full animate-ping"
                  style={{
                    left: `${particle.x}%`,
                    top: `${particle.y}%`,
                    backgroundColor: particle.color,
                    animationDuration: '1s'
                  }}
                />
              ))}

              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <div className="text-center">
                  {selectedTemplate ? (
                    <>
                      <h3
                        className="text-2xl font-bold mb-2"
                        style={{ color: selectedTemplate.color }}
                      >
                        {selectedTemplate.label}
                      </h3>
                      <p className="text-sm text-gray-400 max-w-xs mx-auto">
                        {selectedTemplate.prompt}
                      </p>
                      <div className="flex justify-center gap-2 mt-4 mb-2">
                        {selectedTemplate.tags.map(tag => (
                          <span
                            key={tag}
                            className="px-2 py-1 rounded-full text-xs"
                            style={{
                              backgroundColor: `${selectedTemplate.color}20`,
                              color: selectedTemplate.color
                            }}
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                      {selectedTemplate.adaptation && (
                        <div className="mt-3 flex items-center justify-center gap-2 text-xs text-gray-500">
                          <RotateCw className="w-3 h-3" />
                          <span>{selectedTemplate.adaptation}</span>
                        </div>
                      )}
                    </>
                  ) : (
                    <>
                      <div
                        className="w-24 h-24 rounded-full border-2 border-purple-500/30
                                  flex items-center justify-center mb-4 mx-auto
                                  animate-[pulse_3s_cubic-bezier(0.4,0,0.6,1)_infinite]"
                        style={{ borderColor: '#a855f7' }}
                      >
                        <Zap className="w-8 h-8" style={{ color: '#a855f7' }} />
                      </div>
                      <h3 className="text-xl font-semibold text-gray-600">
                        Select a template
                      </h3>
                    </>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="p-6 border-t border-gray-800 bg-gray-950/50">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-4xl mx-auto">
              {templates.slice(0, 3).map((template, index) => (
                <div
                  key={template.id}
                  className="p-4 rounded-lg border border-gray-700 bg-gray-900/50
                            hover:border-purple-500/50 transition-all duration-200
                            cursor-pointer"
                  onClick={() => handleTemplateSelect(template, index)}
                >
                  <div className="flex items-center gap-3 mb-2">
                  <div
                    className="w-8 h-8 rounded-full flex items-center justify-center"
                    style={{ backgroundColor: `${template.color}20` }}
                  >
                    {(() => {
                      const IconComponent = getIconComponent(template.icon);
                      return <IconComponent className="w-4 h-4" style={{ color: template.color }} />;
                    })()}
                  </div>
                    <h4 className="font-medium text-sm">
                      {template.label}
                    </h4>
                  </div>
                  <p className="text-xs text-gray-400 line-clamp-2 mb-2">
                    {template.prompt}
                  </p>
                  <div className="flex justify-between items-center">
                    <span className="text-xs text-gray-500">
                      Used 0 times
                    </span>
                    <div className="flex gap-1">
                      {template.tags.slice(0, 2).map(tag => (
                        <span
                          key={tag}
                          className="text-xs px-2 py-1 rounded"
                          style={{ backgroundColor: '#374151', color: '#9ca3af' }}
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
