import React, { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowUpRight, BookOpen, Calendar, Check, Code, Command, FileCode, GraduationCap, Link, Search, Sparkles, Target, X, Zap } from 'lucide-react';
import { useGiaStore } from '../store/useGiaStore';
import { templateLearning } from '../services/TemplateLearning';

interface RecommendedTemplate {
  id: string;
  label: string;
  prompt: string;
  color: string;
  icon: string;
  tags: string[];
  relevanceScore: number;
  adaptation?: string;
  difficulty?: string;
  isAutoGenerated?: boolean;
  usageCount: number;
}

interface TemplateSelectorProps {
  isOpen: boolean;
  onClose: () => void;
}

const ICON_MAP: Record<string, React.ComponentType<{ size?: number; className?: string; style?: React.CSSProperties }>> = {
  zap: Zap,
  clock: Command,
  target: Target,
  'rotate-cw': Sparkles,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  code: Code,
  link: Link,
  calendar: Calendar,
  bug: Target,
  'git-branch': Command,
  'file-code': FileCode,
  sparkles: Sparkles,
};

const CATEGORIES = ['All', 'Study', 'Coding', 'Research', 'Planning', 'Automation', 'Made for you'] as const;
type Category = typeof CATEGORIES[number];

function matchesCategory(template: RecommendedTemplate, category: Category): boolean {
  if (category === 'All') return true;
  if (category === 'Made for you') return Boolean(template.isAutoGenerated || template.usageCount > 0);
  if (category === 'Coding') return template.tags.some(tag => /code|debug|typescript|git|performance|optimization/.test(tag));
  if (category === 'Study') return template.tags.some(tag => /study|test|exam|revision/.test(tag));
  if (category === 'Research') return template.tags.some(tag => /web|research|content|summary/.test(tag));
  if (category === 'Planning') return template.tags.some(tag => /planning|schedule|productivity/.test(tag));
  return template.tags.some(tag => /automation|workflow|responses/.test(tag));
}

export const TemplateSelector: React.FC<TemplateSelectorProps> = ({ isOpen, onClose }) => {
  const [templates, setTemplates] = useState<RecommendedTemplate[]>([]);
  const [userContext, setUserContext] = useState<Record<string, unknown> | null>(null);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState<Category>('All');

  useEffect(() => {
    if (isOpen) {
      initializeTemplates();
      setQuery('');
      setCategory('All');
    }
  }, [isOpen]);

  const initializeTemplates = () => {
    const hours = new Date().getHours();
    const timeOfDay = hours < 12 ? 'morning' : hours < 18 ? 'afternoon' : 'evening';
    const ctx: Record<string, unknown> = {
      currentModule: useGiaStore.getState().currentModule,
      recentTopics: [],
      activeTools: [],
      timeOfDay,
      device: window.innerWidth < 768 ? 'mobile' : 'desktop',
      sessionId: 'session-' + Date.now(),
    };
    setUserContext(ctx);

    const personalized = templateLearning.getAllTemplates()
      .map(template => ({
        ...template,
        relevanceScore: template.relevanceScore ?? 0.5,
        usageCount: template.frequency ?? 0,
        adaptation: template.isAutoGenerated ? 'Created from your usage patterns' : undefined,
      }))
      .sort((a, b) => (b.usageCount - a.usageCount) || (b.relevanceScore - a.relevanceScore));

    setTemplates(personalized);
  };

  const visibleTemplates = useMemo(() => {
    const normalizedQuery = query.trim().toLowerCase();
    return templates.filter(template => (
      matchesCategory(template, category)
      && (!normalizedQuery || `${template.label} ${template.prompt} ${template.tags.join(' ')}`.toLowerCase().includes(normalizedQuery))
    ));
  }, [templates, category, query]);

  const handleTemplateSelect = (template: RecommendedTemplate) => {
    templateLearning.recordTemplateUse(template.id, userContext || {});
    useGiaStore.getState().setPendingInput(template.prompt, { autoSend: false });
    onClose();
  };

  if (!isOpen) return null;

  const featuredTemplate = visibleTemplates[0];

  return (
    <AnimatePresence>
      <motion.div
        className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 backdrop-blur-md sm:items-center sm:p-5"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}
      >
        <motion.section
          role="dialog"
          aria-modal="true"
          aria-label="Prompt templates"
          initial={{ opacity: 0, y: 24, scale: 0.98 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 18, scale: 0.985 }}
          transition={{ type: 'spring', stiffness: 300, damping: 30 }}
          className="relative flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-[28px] border sm:max-h-[86vh] sm:max-w-3xl sm:rounded-[28px]"
          style={{
            background: 'linear-gradient(145deg, rgba(24,20,38,0.98), rgba(10,12,20,0.99) 52%)',
            borderColor: 'rgba(167,139,250,0.2)',
            boxShadow: '0 32px 100px rgba(0,0,0,0.6), 0 0 60px rgba(124,58,237,0.12)',
          }}
        >
          <div className="pointer-events-none absolute -right-16 -top-28 h-72 w-72 rounded-full blur-3xl" style={{ background: 'rgba(139,92,246,0.12)' }} />
          <header className="relative flex items-start gap-3 border-b px-5 pb-4 pt-5 sm:px-7 sm:pt-6" style={{ borderColor: 'rgba(255,255,255,0.07)' }}>
            <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border" style={{ background: 'linear-gradient(145deg, rgba(168,85,247,0.22), rgba(99,102,241,0.12))', borderColor: 'rgba(192,132,252,0.25)', color: '#d8b4fe', boxShadow: '0 0 28px rgba(168,85,247,0.14)' }}>
              <Sparkles size={18} />
            </div>
            <div className="min-w-0 flex-1">
              <div className="flex flex-wrap items-center gap-2">
                <h2 className="text-base font-bold tracking-tight sm:text-lg" style={{ color: 'var(--gia-text)' }}>Prompt studio</h2>
                <span className="rounded-full border px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.12em]" style={{ borderColor: 'rgba(168,85,247,0.25)', background: 'rgba(168,85,247,0.1)', color: '#c4b5fd' }}>Templates</span>
              </div>
              <p className="mt-1 text-[11px] leading-relaxed sm:text-xs" style={{ color: 'var(--gia-muted)' }}>Strong starting points, ready to personalize in your composer.</p>
            </div>
            <button type="button" onClick={onClose} aria-label="Close templates" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border transition-colors hover:bg-white/5" style={{ borderColor: 'rgba(255,255,255,0.08)', color: 'var(--gia-muted)' }}>
              <X size={16} />
            </button>
          </header>

          <div className="relative space-y-4 overflow-y-auto px-4 py-4 sm:px-7 sm:py-5">
            <label className="flex items-center gap-2.5 rounded-2xl border px-3.5 py-3 transition-colors focus-within:border-violet-400/40" style={{ background: 'rgba(255,255,255,0.035)', borderColor: 'rgba(255,255,255,0.08)' }}>
              <Search size={15} style={{ color: '#a78bfa' }} />
              <input
                value={query}
                onChange={event => setQuery(event.target.value)}
                placeholder="Find a starting point…"
                aria-label="Search templates"
                className="min-w-0 flex-1 bg-transparent text-xs outline-none placeholder:text-slate-500"
                style={{ color: 'var(--gia-text)' }}
              />
              <kbd className="hidden rounded-md border px-1.5 py-0.5 text-[9px] sm:inline" style={{ borderColor: 'rgba(255,255,255,0.1)', color: 'var(--gia-muted-2)' }}>SEARCH</kbd>
            </label>

            <nav aria-label="Template categories" className="flex gap-1.5 overflow-x-auto pb-1 [&::-webkit-scrollbar]:hidden">
              {CATEGORIES.map(item => {
                const active = category === item;
                return (
                  <button
                    key={item}
                    type="button"
                    onClick={() => setCategory(item)}
                    aria-pressed={active}
                    className="shrink-0 rounded-full border px-3 py-1.5 text-[10px] font-medium transition-all"
                    style={{
                      borderColor: active ? 'rgba(167,139,250,0.42)' : 'rgba(255,255,255,0.07)',
                      color: active ? '#ddd6fe' : 'var(--gia-muted)',
                      background: active ? 'rgba(139,92,246,0.16)' : 'rgba(255,255,255,0.02)',
                      boxShadow: active ? 'inset 0 0 18px rgba(139,92,246,0.08)' : undefined,
                    }}
                  >
                    {item}
                  </button>
                );
              })}
            </nav>

            {featuredTemplate && category === 'All' && !query && (
              <button
                type="button"
                onClick={() => handleTemplateSelect(featuredTemplate)}
                className="group relative w-full overflow-hidden rounded-2xl border p-4 text-left transition-transform hover:-translate-y-0.5 sm:p-5"
                style={{ background: `linear-gradient(115deg, ${featuredTemplate.color}20, rgba(18,19,30,0.92) 68%)`, borderColor: `${featuredTemplate.color}40` }}
              >
                <div className="pointer-events-none absolute -right-5 -top-10 h-40 w-40 rounded-full blur-3xl" style={{ background: `${featuredTemplate.color}25` }} />
                <div className="relative flex items-start gap-3">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border" style={{ background: `${featuredTemplate.color}20`, borderColor: `${featuredTemplate.color}35`, color: featuredTemplate.color }}>
                    {React.createElement(ICON_MAP[featuredTemplate.icon] || Sparkles, { size: 18 })}
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <span className="text-[9px] font-semibold uppercase tracking-[0.15em]" style={{ color: featuredTemplate.color }}>Picked for you</span>
                      {featuredTemplate.isAutoGenerated && <span className="text-[9px]" style={{ color: '#c4b5fd' }}>Personalized</span>}
                    </div>
                    <h3 className="mt-1 text-sm font-semibold" style={{ color: 'var(--gia-text)' }}>{featuredTemplate.label}</h3>
                    <p className="mt-1 line-clamp-2 text-[11px] leading-relaxed" style={{ color: 'var(--gia-muted)' }}>{featuredTemplate.prompt}</p>
                  </div>
                  <span className="mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" style={{ borderColor: `${featuredTemplate.color}35`, color: featuredTemplate.color }}><ArrowUpRight size={15} /></span>
                </div>
              </button>
            )}

            <div className="flex items-center justify-between px-0.5">
              <div>
                <h3 className="text-[11px] font-semibold" style={{ color: 'var(--gia-text)' }}>{query || category !== 'All' ? 'Matching templates' : 'Explore templates'}</h3>
                <p className="mt-0.5 text-[9px]" style={{ color: 'var(--gia-muted-2)' }}>{visibleTemplates.length} ready-to-edit starting points</p>
              </div>
              <span className="text-[9px]" style={{ color: 'var(--gia-muted-2)' }}>Your frequent picks rise to the top</span>
            </div>

            {visibleTemplates.length === 0 ? (
              <div className="rounded-2xl border px-4 py-9 text-center" style={{ borderColor: 'rgba(255,255,255,0.07)', background: 'rgba(255,255,255,0.02)' }}>
                <Search size={19} className="mx-auto" style={{ color: 'var(--gia-muted-2)' }} />
                <p className="mt-2 text-xs font-medium" style={{ color: 'var(--gia-text)' }}>No matching templates</p>
                <p className="mt-1 text-[10px]" style={{ color: 'var(--gia-muted)' }}>Try another search or category.</p>
              </div>
            ) : (
              <div className="grid gap-2 sm:grid-cols-2">
                {visibleTemplates.map((template, index) => {
                  const Icon = ICON_MAP[template.icon] || Sparkles;
                  return (
                    <motion.button
                      key={template.id}
                      type="button"
                      onClick={() => handleTemplateSelect(template)}
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: Math.min(index, 8) * 0.025 }}
                      className="group flex min-h-32 flex-col rounded-2xl border p-3.5 text-left transition-all hover:-translate-y-0.5"
                      style={{ background: 'linear-gradient(145deg, rgba(255,255,255,0.035), rgba(255,255,255,0.012))', borderColor: 'rgba(255,255,255,0.075)' }}
                    >
                      <div className="flex w-full items-start gap-2.5">
                        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl" style={{ background: `${template.color}1a`, color: template.color }}>
                          <Icon size={15} />
                        </div>
                        <div className="min-w-0 flex-1">
                          <div className="flex items-center gap-1.5">
                            <h4 className="truncate text-[11px] font-semibold" style={{ color: 'var(--gia-text)' }}>{template.label}</h4>
                            {template.isAutoGenerated && <Sparkles size={10} className="shrink-0" style={{ color: '#c4b5fd' }} />}
                          </div>
                          <p className="mt-1 line-clamp-2 text-[10px] leading-relaxed" style={{ color: 'var(--gia-muted)' }}>{template.prompt}</p>
                        </div>
                        <ArrowUpRight size={13} className="shrink-0 opacity-0 transition-opacity group-hover:opacity-70" style={{ color: template.color }} />
                      </div>
                      <div className="mt-auto flex w-full items-center justify-between gap-2 pt-3">
                        <span className="text-[9px]" style={{ color: 'var(--gia-muted-2)' }}>
                          {template.usageCount > 0 ? `Used ${template.usageCount} time${template.usageCount === 1 ? '' : 's'}` : 'Not used yet'}
                        </span>
                        <span className="flex items-center gap-1 text-[9px] font-medium opacity-70 group-hover:opacity-100" style={{ color: template.color }}>
                          <Check size={10} /> Add to composer
                        </span>
                      </div>
                    </motion.button>
                  );
                })}
              </div>
            )}
          </div>
          <footer className="relative flex items-center justify-between border-t px-5 py-3 sm:px-7" style={{ borderColor: 'rgba(255,255,255,0.07)', background: 'rgba(0,0,0,0.14)' }}>
            <p className="text-[9px]" style={{ color: 'var(--gia-muted-2)' }}>Selecting a template puts it in the composer—you stay in control.</p>
            <button type="button" onClick={onClose} className="rounded-lg px-2.5 py-1.5 text-[10px] font-medium transition-colors hover:bg-white/5" style={{ color: 'var(--gia-muted)' }}>Close</button>
          </footer>
        </motion.section>
      </motion.div>
    </AnimatePresence>
  );
};
